### ISSUE TITLE
How to record system sound and microphone input sound at the same time？

### ISSUE THREAD

**Issue by ThemanerL** [baSSiLL/SharpAvi#21]

**Comment by baSSiLL** [comment]
Hi
This question is not directly related to SharpAvi, because this library does not capture audio. It only allows to write audio data that you already got somewhere. In a sample app I used NAudio to capture from the mic. It is also possible to capture audio being played back - check the link in other issue
https://github.com/baSSiLL/SharpAvi/issues/11
Then depending on your requirements you can either add 2 separate audio streams to AviWriter or combine audio data from 2 sources into a single audio stream.
Also you may check solutions like [Virtual Audio Cable](https://software.muzychenko.net/eng/vac.htm) which probably can combine playback and mic to a single virtual audio input. So you can actually capture from a single source.

**Comment by ThemanerL** [comment]
Thank you very much, I'll try my best.
