### ISSUE TITLE
how to close the video at the end of the process

### ISSUE THREAD

**Issue by dorathoto** [baSSiLL/SharpAvi#41]
when I use the MotionJpeg codec even if the computer restarts during recording, the video is correct.

However when I use x264 the file seems to be without end and does not play.
Even though it is a software restart (`shutdown / r / t 10`)

On windows

**Comment by baSSiLL** [comment]
I guess that's because x264 caches some data which needs to be flushed to a file for it to be played correctly.
Anyway, your question relates more to communication of the program with OS rather than to writing a video. That is, an ability to gracefully end program operations (in your case, finalize the video) on OS shutdown/restart.
Check [SystemEvents](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents) class, and its **SessionEnding** and **SessionEnded** events.
